### ISSUE TITLE
Timekeeper threads build up over time

### ISSUE THREAD

**Issue by terite** [spherous/HexChess#25]
`Timekeeper` threads are not stopped in all cases. This leads to a situation where many orphaned timekeeper threads will be alive in the background doing almost (but not quite) nothing. This can be easily demonstrated by: 
1. Give Timekeeper threads distinct names.
2. Do things like load a few games, go back to the menu a few times, etc.
3. Enumerate active threads and observe Timekeeper threads with distinct names.

**Comment by spherous** [comment]
Fixed in commits: 
39dba9bbe66c32e085fa74b20a76cf92faf87ca0 
e70432eacf7c9d222abd176095085b1f0a6b3e82

Wrapped threads in a new class TrackedThread to make looking up all existing threads much easier. This maintains a static list of all tracked threads.

Timekeepers should now properly terminate threads upon reaching the end of a game.
Board will "Kill" an existing game when loading a new one, this will terminate threads.

If using API without Unity, Game.KillGame() must be called if you're ending a non-complete game to properly shutdown threads when swapping games. This call is not needed if the game ends naturally: stalemate, flagfall, surrender, insufficient material, 5 fold repetition, 50 move rule, or checkmate.

I also added a destructor to Game that calls KillGame() to catch any that may slip through the cracks.
